# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://teachwithqualdata.org/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Teaching with Qualitative Data
# Description of the Site
description: Bringing Qualitative Data to the Methods Classroom
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: academic, qualitative research, data
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/focusgroup.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: qdr@syr.edu
facebook_username:
twitter_username: qdrepository
instagram_username:
github_username:  QualitativeDataRepository
youtube_channel_id:


# Google Analytics
google-analytics:


organization-name: Qualitative Data Repository
organization-image: /assets/images/qdr-logo.png
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
organization-url: https://qdr.syr.edu
# Name of the Author
author1-name: Diana Kapiszewski
# URL for the Image of the Author
author1-image: /assets/images/kapiszewski-diana.png

author1-about: >-
  <strong>Diana Kapiszewski</strong> is Provost’s Distinguished Associate Professor of Government at Georgetown University. She studies law and legal institutions in Latin America, and qualitative research methods. Her book <em>High Courts and Economic Governance in Argentina and Brazil</em> (Cambridge, 2012) received the APSA Law and Courts Section's C. Herman Pritchett Award. She has co-edited <em>Consequential Courts: Judicial Roles in Global Perspective</em> (Cambridge, 2013), <em>Beyond High Courts: The Justice Complex in Latin America</em> (Notre Dame, 2019). In the area of research methods, Kapiszewski, co-authored <em>Field Research in Political Science: Practices and Principles</em> (Cambridge, 2015), serves as Director of Research for the Qualitative Data Repository and co-edits Cambridge's “Methods for Social Inquiry” book series.

# Name of the Author
author2-name: Sebastian Karcher
# URL for the Image of the Author
author2-image: /assets/images/karcher-sebastian.jpg

author2-about: >-
  <strong>Sebastian Karcher</strong> is the Associate Director of the Qualitative Data Repository and Research Assistant Professor of Political Science at Syracuse University. His main interests are in research transparency, management and curation of qualitative data, and the integration of technology into scholarly workflows. He is an active contributor to several scholarly open source projects such as Zotero and the Citation Style Language, and has taught widely on digital technology and data management. He has published in both social science journals such as <em>International Studies Quarterly</em> and <em>Socio-Economic Review</em> and information science journals such as <em>Nature Scientific Data</em> and <em>Data Science Journal</em>.

# Name of the Author
author3-name: Jessica Lester
# URL for the Image of the Author
author3-image: /assets/images/lester-jessica.jpg
author3-about: >-
  <strong>Jessica Nina Lester</strong> is an Associate Professor of Inquiry Methodology (Qualitative Research) in the School of Education at Indiana University, Bloomington. Dr. Lester has published over 80 peer-reviewed journal articles, as well as numerous books and book chapters focused on discourse and conversation analysis, disability studies, and more general concerns related to qualitative research. She is a co-author of the first edition of Digital Tools for Qualitative Research, published with SAGE. In 2014, Dr. Lester received AERA's Division D's Early Career Award in Measurement and Research Methodology (Qualitative Methodology) and has also won several teaching awards at Indiana University. She has most recently published in journals such as <em>Qualitative Inquiry</em>, <em>Qualitative Research</em>, and <em>Discourse Studies</em>.

# 60 Words About the Author
project-about: This project examines the pedagogical practices and effects on learning of using data to teach qualitative analytic methods at the graduate level in the social sciences and beyond. Our research entails a broad survey of methods instructors in multiple disciplines, observing classroom instruction, surveying students, interviewing instructors and students, and assessing course materials. Aiming for cross-field impact on qualitative methods instruction, the project will develop training materials, guidelines, and lesson plans for integrating shared qualitative data into graduate research methods courses. Our ultimate goal is transforming the instruction of qualitative methods, and thereby the conduct, rigor, and contributions of qualitative research.


site-about: This site is maintained by the Qualitative Data Repository (QDR).

research1: In 2020, we surveyed instructors of graduate research methods courses in education, health, political science, and sociology at 250 US universities regarding their teaching practices. Initial findings show that instructors often use qualitative data to teach research methods (typically their own rather than shared data) and that they believe teaching with data improves student learning. (with Beatriz Rey; funded by a Syracuse University CUSE grant)
research2: A second funded study (started Fall 2021) examines and compares the teaching and learning of thematic analysis in two graduate-level qualitative methods courses in education research programs at different institutions using class observations and participant interviews. (with Darcy Furlong; funded by an Indiana University SSRC grant)

resource1: The Qualitative Data Repository has curated a <a href="https://qdr.syr.edu/guidance/teaching/data-for-teaching">list of data projects particularly well suited for teaching</a>.
  
resource2: The UK Data Archive has produced <a href="https://ukdataservice.ac.uk/learning-hub/teach-with-real-data/#teaching-resources-qualitative-data">resources for teaching with qualitative data</a> it archives.

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
